### PR TITLE
Update chapter6.md

### PR DESCRIPTION
**Pull request by ndvanforeest**
To prevent white space issues I decided to edit the file on github.

### CODE REVIEW

**Comment by pronoiac** [comment]
I think I fixed the whitespace issues we tripped over before, so feel free to try local branches and commits and stuff.

**Comment by pronoiac** [comment]
I expected `ticks`?

**Comment by pronoiac** [comment]
And the previous line changed in #172 , so merge conflict, and I think I'll just tweak this.

**Comment by ndvanforeest** [comment]
Actually I followed your suggestion (and it was kind of weird that I found the first "is" without quotes, but missed the one you found). 

BTW, it's a great book. I really like reading it. Thanks for helping making this book available.

**Pull request closed without merging**
