### PR TITLE
Remade diagrams

### PR DESCRIPTION
**Pull request by pronoiac**
I puttered around on draw.io / diagrams.net . I think they're an improvement, but perhaps not the final word. I included svg (vector) and png files. 

The text in svg *might* be an issue - embedding fonts (which might be the default?) or turning the letters into lines and curves could fix that. Those would be a matter of re-exporting with different settings, after verifying the fix. I ... dunno. Maybe roll forward with this until it breaks somewhere? 

Some background in #139 .

### CODE REVIEW

**Comment by norvig** [comment]
I'm willing to try going forward for this. We should test on multiple browser/OS combinations. Thank you for the effort.

**Comment by norvig** [comment]
Note: Fig 17.5 still needs work.

**Comment by pronoiac** [comment]
Re: 17.5 - Turning some images into markdown tables is still a WIP branch - see #136. It might have stalled. 

I realized I have a Raspberry Pi, with only the basic Ubuntu fonts installed. I'm going to skim the diagrams there.

**Comment by pronoiac** [comment]
On the Linux machine, the diagrams are perfectly legible and in place. (Everything looks odd at 500% zoom.) 18.05 had inconsistent fonts, but in all, it looks good!

**Pull request merged**
