### PR TITLE
add paip.asd and modify some lisp files to load it using asdf.

### PR DESCRIPTION
**Pull request by snmsts**
Tested with asdf 3.3.1 with sbcl 1.4.2 aarch64.

### CODE REVIEW

**Comment by norvig** [comment]
I designed my `requires` interface in 1990, when CL was quite different than it is now. If someone has a better idea for implementing `requires`, I'm all for it.

**Comment by arademaker** [comment]
I have a course 2 years ago and made part of the code loadable via quicklisp

**Comment by snmsts** [comment]
@norvig  Thank you for merging it.

I think current ``requires`` definition is a bit old fashioned but acceptable. it works and the only two problems I can see from today's view point are it might be just a bit slow load and execute cause it isn't compiled automatically and the other problem is not organized in packages.

1. cpu and memory are much improved in this 20 years.
1. expected users/readers are not accustomed with common lisp,so tricked by lisp concepts is not a focus here.
1. I tried a bit and find out I need to change source code other than ``auxfns.lisp`` (eg. rename same named functions in a file which are intentionally named to show better implementation.)


@arademaker looks great work. I'll register this repository to ``quicklisp`` official dist. I felt use a lot of short common name is not favorable (like ``UTILS``.)

**Comment by Hexstream** [comment]
ASDF has been the (essentially) uncontested Common Lisp loading standard for quite a while, I think using it instead of `require` would be far preferable, especially to help newbies and to fight the bit-rot that is all too prevalent in the Common Lisp community generally. And maybe using this approach of modernization can help inspire further modernization in other projects.

**Comment by arademaker** [comment]
Same arguments for using quicklisp !

**Comment by olopierpa** [comment]
Please do not make PAIP code depend on ASDF. Pretty please.

**Comment by arademaker** [comment]
Can you provide arguments ?

**Comment by olopierpa** [comment]
On Sat, Mar 3, 2018 at 8:56 PM, Alexandre Rademaker <
notifications@github.com> wrote:

> Can you provide arguments ?
>

I think arguments are needed for creating a dependence on a big chunk of
extraneous code, and for no reasons.

**Comment by Hexstream** [comment]
ASDF is a "free" dependency, since 100% of "modern" Common Lisp code depends on it.

(Quicklisp also requires ASDF.)

**Comment by snmsts** [comment]
@Hexstream 

in case you missed my intention here.

What I mean by ``acceptable`` here is 

1. I've already write asd file for this project to provide ``paip:requires`` function loadable via asdf which are different from [cl:require](http://www.lispworks.com/documentation/lw70/CLHS/Body/f_provid.htm)
1. by the ``paip:requires``, I confirm codes are loadable.(I don't know everything is perfectly works or not.)
1. To do it,I had to edit ``auxfns.lisp`` a bit, but I believe it was subtle impact as a whlole.
1. To support asdf completely means to be able to compile every peace of code. compiler is not lenient so I shouldn't change a lot.
1. that kind of modernization is not the point of text book and PAIP code is not the library everyone want to depend on.
1. Draw back for text is not a little. **So I stop here**.

I felt you are just promoting ASDF's importance here.
It doesn't make sense for learners for PAIP if it breaks code.
What is this pull request? Didn't I make it?  Why my patch is not sufficient for you?
If you have specific point to improve, please make a new issue.

@olopierpa 👍

**Comment by Hexstream** [comment]
@snmsts

???????????? I thoroughly do not understand. My biggest confusion of 2018 thus far...

You made a pull request adding support for ASDF, @olapierpa was apparently against it, I was *for* it, I explained that ASDF (and thus your patch) is the way to go...

I absolutely can't make sense of your message in this context, at all.

**Pull request merged**
