### PR TITLE
Import chapters from cleaner source

### PR DESCRIPTION
**Pull request by pronoiac**
Overall I think it's a better foundation to work from.

Note, this impacts chapters that have already had a draft done, and it's a regression for those.

### CODE REVIEW

**Comment by norvig** [comment]
After looking at a sampling of the chapters, I agree this is the best way forward. 

Is there any way to salvage the work that was done previously?

**Comment by norvig** [comment]
How about cleaning up the `[ ](#){:#l0015}` and `!!!(p) {:.unnumlist}` ?

**Comment by pronoiac** [comment]
I'll look into removing the likes of `#l0015` and `.unnumlist`. Properly handling code blocks appears non-trivial. 

For salvaging previous work: the best path I see is going over and incorporating diffs (well, `wdiff`). I've almost completed an ascii filter, which should lessen diff noise from things like smart quotes and *three* different types of hyphen.

**Comment by casouri** [comment]
Is there any way to improve the importing tool?

**Comment by pronoiac** [comment]
@casouri: Yes, there's more info in issue #48.

**Pull request merged**
