### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by nticaric**

### CODE REVIEW

**Comment by PuercoPop** [comment]
Regarding commit: https://github.com/norvig/paip-lisp/pull/7/commits/17bceafea4f7a01d

Form Feeds marked the end of every page. If one would want to split the the text into multiple files it seems   a bad idea to remove page delimiters.

**Comment by nticaric** [comment]
@PuercoPop I guess if someone wants to split the text into multiple files it would be better to do it by chapter not by page break. In my opinion the page breaks that were contained in the text file make only sense for a print version of the book.

**Comment by Hexstream** [comment]
I think ideally, in an eventual HTML version especially, you'd want to have an easy way to determine from what page of the original book each part of the text is from, and have a direct link to the PDF for that page (preferably a single-page PDF), for easy auditing purposes.

For instance, I did something similar to this while developing a similar project. At https://clos-mop.hexstreamsoft.com/concepts/, you can see that there's the page references on the left. While in development, each such page number linked to a photo of the page from the original physical book, opening in a new tab.

(For now this has been removed from the production version because of copyright concerns, while chapters 5 and 6 are public domain, I'm not completely sure of the legal status of pictures of renderings of the pages from the original overall copyrighted book. Gah.)

This arrangement made it very easy to carefully audit the HTML content against the actual book, side-by-side, ensuring that there are no errors or omissions. This was also very invaluable for actually understanding the structure of the book while in development.

**Comment by miyuchina** [comment]
I was also using page breaks to count page numbers. The page numbers can then be used to separate chapters, since each page correspond to a page in the print book, and it is easier to find chapter breaks in the print book. See [this script](https://gist.github.com/miyuchina/e6dbbe482e09a91cdab965e222034dc1).

It'd be more difficult splitting chapters directly in the text file itself, since some of the chapter titles are gobbled with wrong characters.

**Comment by nticaric** [comment]
ok, I proposed another pull request that adds back the form feed https://github.com/norvig/paip-lisp/pull/8

**Pull request merged**
