### PR TITLE
Update chapters 4-6

### PR DESCRIPTION
**Pull request by ndvanforeest**
typo

### CODE REVIEW

**Comment by pronoiac** [comment]
Looking good so far! Are you done with the chapter?

**Comment by ndvanforeest** [comment]
Actually, I found many more such small typos, but I did not know whether there would be any interest in repairing them. If so, I would be happy to contribute.

**Comment by pronoiac** [comment]
I'd love to see more typos corrected! 

(I'd suggest a commit per chapter, or batch of typos, though.)

**Comment by ndvanforeest** [comment]
Sure. I'll continue with ch 4.

One thing surprised me. `nil` is sometimes between back tics, but not
always. Is this on purpose? Likewise, should it be `t`, or just `t`, or
`T`, or T?

**Comment by pronoiac** [comment]
Good question! I don't have an articulate answer for that off-hand. @norvig, thoughts?

**Comment by ndvanforeest** [comment]
For the moment I focus on ch 6, hence it will take some time before I return to ch 4 and ch 5. If ok with you, please close this pr.

**Comment by norvig** [comment]
I think it should be `t` in tickmarks when discussing input; `T` when discussing output.

**Comment by pronoiac** [comment]
Too many (automated?) edits were accidentally included in the commit "tickmarks" - mostly whitespace edits. Some were good, like removing trailing spaces, some less so. I think I'm going to revert tabs to spaces (referencing the scan, I *think* it should be 8 spaces per tab?), and the `eliza1.lisp` edits. You don't need to do anything; I plan to include that work as I merge this.

Some notes on git: 
I'd suggest working from branches: `git checkout -b tickmarks` or the like, before you start editing. It makes it easier to juggle multiple angles of attack independently of each other. 

I usually add to staging with `git add -p` , which lets me verify I'm intending only what I intend to add.

**Comment by pronoiac** [comment]
Merged!

**Comment by pronoiac** [comment]
Cool! Sorry it didn't work; glancing at the man pages, that looks like it ought to work? Dunno.

**Pull request merged**
